# Generated by Django 4.1.7 on 2024-09-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_category_notification_comment_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Notification'},
        ),
    ]
